name: TDIFF - SPECTRUM 2

on:
  workflow_dispatch:
  pull_request:

jobs:
  tdiff:
    uses: ./.github/workflows/_tdiff.yml
    with:
      root: beta      # the spectrum-tokens data we want to compare against (branch of the repo)
    secrets: inherit